spring:
  profiles:
    active: dev
  application:
    name: web-deploy
  servlet:
    multipart:
      enabled: true
      max-file-size: 20971520
      max-request-size: 20971520
      location: /temp
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  resources:
    chain:
      cache: false
  thymeleaf:
    cache: false
    check-template-location: false
    enabled: true
    encoding: UTF-8
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
mybatis-plus:
  mapper-locations: classpath*:/com/github/huzhihui/webdeploy/mapper/*Mapper.xml
