package com.github.huzhihui.webdeploy.entity;

import java.io.Serializable;
import java.util.Date;

public class Project implements Serializable {
    /**  | 表字段 id */
    private String id;

    /** 项目名称 | 表字段 name */
    private String name;

    /** 终端ID */
    private String endpointId;

    /** 根目录 | 表字段 root_folder */
    private String rootFolder;

    /** 发布文件夹名称 | 表字段 deploy_folder */
    private String deployFolder;

    /** 压缩解压后的文件夹名称 用来校验文件格式用 | 表字段 package_folder */
    private String packageFolder;

    /** 状态  10：启用  20：禁用 | 表字段 use_flag */
    private Integer useFlag;

    /**  | 表字段 create_time */
    private Date createTime;

    /**  | 表字段 update_time */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getRootFolder() {
        return rootFolder;
    }

    public void setRootFolder(String rootFolder) {
        this.rootFolder = rootFolder;
    }

    public String getDeployFolder() {
        return deployFolder;
    }

    public void setDeployFolder(String deployFolder) {
        this.deployFolder = deployFolder;
    }

    public String getPackageFolder() {
        return packageFolder;
    }

    public void setPackageFolder(String packageFolder) {
        this.packageFolder = packageFolder;
    }

    public Integer getUseFlag() {
        return useFlag;
    }

    public void setUseFlag(Integer useFlag) {
        this.useFlag = useFlag;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getEndpointId() {
        return endpointId;
    }

    public void setEndpointId(String endpointId) {
        this.endpointId = endpointId;
    }
}
