spring:
  profiles:
    active: dev
  application:
    name: web-deploy-slave
  servlet:
    multipart:
      enabled: true
      max-file-size: 20971520
      max-request-size: 20971520
      location: /temp
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
