package com.github.huzhihui.webdeploy.entity;

import java.io.Serializable;
import java.util.Date;

public class DeployHistory implements Serializable {
    /**  | 表字段 id */
    private String id;

    /** 终端ID | 表字段 endpoint_id */
    private String endpointId;

    /** 终端名称 | 表字段 endpoint_name */
    private String endpointName;

    /** 项目ID | 表字段 project_id */
    private String projectId;

    /** 项目名称 | 表字段 project_name */
    private String projectName;

    /** 状态：10失败，20：成功 | 表字段 status */
    private Integer status;

    /** 描述 | 表字段 describe */
    private String describe;

    /** 历史文件夹 | 表字段 his_file_name */
    private String hisFileName;

    /** 操作人名称 | 表字段 oper_user_cname */
    private String operUserCname;

    /** 创建时间 | 表字段 create_time */
    private Date createTime;

    /** 执行日志 | 表字段 oper_log */
    private String operLog;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table deploy_history
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getEndpointId() {
        return endpointId;
    }

    public void setEndpointId(String endpointId) {
        this.endpointId = endpointId;
    }

    public String getEndpointName() {
        return endpointName;
    }

    public void setEndpointName(String endpointName) {
        this.endpointName = endpointName;
    }

    public String getProjectId() {
        return projectId;
    }

    public void setProjectId(String projectId) {
        this.projectId = projectId;
    }

    public String getProjectName() {
        return projectName;
    }

    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getDescribe() {
        return describe;
    }

    public void setDescribe(String describe) {
        this.describe = describe;
    }

    public String getHisFileName() {
        return hisFileName;
    }

    public void setHisFileName(String hisFileName) {
        this.hisFileName = hisFileName;
    }

    public String getOperUserCname() {
        return operUserCname;
    }

    public void setOperUserCname(String operUserCname) {
        this.operUserCname = operUserCname;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public String getOperLog() {
        return operLog;
    }

    public void setOperLog(String operLog) {
        this.operLog = operLog;
    }
}