package com.github.huzhihui.webdeploy.entity;

import java.io.Serializable;
import java.util.Date;

public class EndpointProjectRela implements Serializable {
    /**  | 表字段 id */
    private String id;

    /** 终端ID | 表字段 endpoint_id */
    private String endpointId;

    /** 项目ID | 表字段 project_id */
    private String projectId;

    /**  | 表字段 create_time */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table endpoint_project_rela
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getEndpointId() {
        return endpointId;
    }

    public void setEndpointId(String endpointId) {
        this.endpointId = endpointId;
    }

    public String getProjectId() {
        return projectId;
    }

    public void setProjectId(String projectId) {
        this.projectId = projectId;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}